# Config for https://github.com/toolmantim/release-drafter
name-template: 'Play Ebean, This module provides Ebean support for Play Framework.'
tag-template: '$NEXT_PATCH_VERSION'

change-template: '- $TITLE #$NUMBER by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes
  $CHANGES
