name: Publish

on:
  push:
    branches: # Snapshots
      - main
    tags: ["**"] # Releases

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@unblock-repo_scala_sbt_org
    secrets: inherit
